//part1_interaction_click
$("#tablet_btn").click(function(event){
  $("#tablet").addClass("visible");
})
//part2_interaction_click
$("#exporterbtn").click(function(event){
  $("#export_text").addClass("click");
  $("#Exp_button").addClass("click");
  $("#emport_pic1").addClass("show");
})
$("#importerbtn").click(function(event){
  $("#import_text").addClass("click");
  $("#Imp_button").addClass("click");
  $("#export_text").removeClass("click");
  $("#Exp_button").removeClass("click");
  $("#emport_pic1").addClass("hide");
  $("#import_pic1").addClass("show");

})
//part3_interaction_click
$("#avocado_btn").mouseenter(function(event){
  $("#water_avocado").addClass("show");
})
$("#avocado_btn").mouseleave(function(event){
  $("#water_avocado").removeClass("show");
})
$("#tomato_btn").mouseenter(function(event){
  $("#water_tomato").addClass("show");
})
$("#tomato_btn").mouseleave(function(event){
  $("#water_tomato").removeClass("show");
})
$("#orange_btn").mouseenter(function(event){
  $("#water_orange").addClass("show");
})
$("#orange_btn").mouseleave(function(event){
  $("#water_orange").removeClass("show");
})
