//part1_interaction_click
$("#tablet_btn").click(function(event){
  $("#tablet").addClass("visible");
})
//part2_interaction_click
$("#exporterbtn").click(function(event){
  $("#export_text").addClass("click");
  $("#Exp_button").addClass("click");
  $("#emport_pic1").addClass("show");
})
$("#importerbtn").click(function(event){
  $("#import_text").addClass("click");
  $("#Imp_button").addClass("click");
  $("#export_text").removeClass("click");
  $("#Exp_button").removeClass("click");
  $("#emport_pic1").addClass("hide");
  $("#import_pic1").addClass("show");

})
$("#tre1").click(function(){
    $(this).addClass('hide');
});
